title: HongYan

name: HongYan's homepage
description:  I am an phD student of Computer Science and Technology in Shanghai Jiao Tong University (SJTU). 
  I major in computer vision and deep learning. Currently, I focus on meta-learning for few-shot image generation. 
  Prior to now, I was a master at SJTU. Before that, I obtained my bachelor degree from Shenzhen University(SZU).
# url: https://www.aiforall.pro
url: https://www.yanhong.fun
github_username:  hy-zpg

# 自定义post url
permalink: /blog/:title.html
timezone: Asia/Shanghai

permalink: blog/:year/:month/:title/
jobtitle: "phD"
excerpt_separator: "<!--more-->"

# Overriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
lsi: false

markdown: kramdown
kramdown:
    input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
    extensions:
    - autolink
    - footnotes
    - smart
hard_wrap: false
#  use_coderay: true
syntax_highlighter: rouge
#  coderay:
#  coderay_line_numbers:  nil

# White-listed plugins
gems:
  - jekyll-sitemap
