# Site settings
title: Hong Yan
email: yanhong.sjtu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am an phD student of Computer Science and Technology in Shanghai Jiao Tong University (SJTU). 
  I major in computer vision and deep learning. Currently, I focus on meta-learning for few-shot image generation. 
  Prior to now, I was a master at SJTU. Before that, I obtained my bachelor degree from Shenzhen University(SZU)
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "https://github.com/hy2628982280/yanhong.github.io" # the base hostname & protocol for your site
url: "https://www.aiforall.pro"
#twitter_username: stevenvmiller
github_username:  hy-zpg
#orcid_id: 0000-0003-4072-6263
#google_scholar_id: BNr-fb8AAAAJ

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
jobtitle: "phD"
excerpt_separator: "<!--more-->"

# SEO stuff
#google_author: "https://plus.google.com/u/0/110288225974212014913"
#google_site_verification: "nfd8hkZSc3GmIivrLCudAdTq5m1kI0Ao7P1UyIt9z5Q"
#bing_webmastertools_id: "E24D33E8D53D5730794478CB209F15E5"

plugins:
  - jekyll-sitemap
